import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Navbar from "./Navbar";
import styles from "../styles/Home.module.css";

export default function Layout({ children, title = "HP by Next.js" }){
    return (
        <div className={styles.container}>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <Navbar />
            </header>
            <main className={styles.main}>
                {children}
            </main>
            <footer className={styles.footer}>
                <a
                    className="flex items-center"
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <Image src="/vercel.svg" alt="Vercel Logo" className="h-4 ml-2" width={72} height={16} />
                </a>
            </footer>
        </div>
    );
}